# Generated by Django 5.2.3 on 2025-06-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена со скидкой')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('reviews_count', models.IntegerField(verbose_name='Количество отзывов')),
                ('query', models.CharField(max_length=255, verbose_name='Поисковый запрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бренд')),
                ('product_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID товара на WB')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'), models.Index(fields=['sale_price'], name='products_pr_sale_pr_78511c_idx'), models.Index(fields=['rating'], name='products_pr_rating_c3ba71_idx'), models.Index(fields=['reviews_count'], name='products_pr_reviews_fd77f8_idx'), models.Index(fields=['query'], name='products_pr_query_64ac3b_idx')],
            },
        ),
    ]
